### ISSUE TITLE
PSR-7 support

### ISSUE THREAD

**Issue by alexeyshockov** [amphp/artax#101]
Thanks for great feature-rich HTTP client implementation!

Do you have any plans for PSR-7 support? Standard request/response interfaces and so on.

**Comment by bwoebi** [comment]
No.

In particular the Streams API of PSR-7 is not compatible with the Promise based API.

It should be easy though, to write a blocking wrapper implementing PSR-7 around Artax. I do not plan to write one, but users are welcome to write their own.

**Comment by kelunik** [comment]
**Further Explanation**

PSR-7's `StreamInterface` doesn't work well in an async context without fully buffering all bodies, defeating the entire purpose of using streams. Major problems are `__toString()`, `getContents()`, etc.

[ReactPHP tried to implement PSR-7 in their HTTP server](https://github.com/reactphp/http/blob/801e8e5357210bcda5a1600dcf852860ccdc8886/src/HttpBodyStream.php), but it's not fully compliant. Most stream methods just throw a `BadMethodCallException`.

In our opinion it doesn't make sense to migrate to such a broken implementation if it can't be fully compatible without breaking basic async principles or the contract.

We have [our own interfaces for streams](https://github.com/amphp/byte-stream) that work well with async that are used across many of our packages.

Additionally, PSR-7 has several weaknesses such as defining streams and URIs inside an HTTP abstraction specification.
