### ISSUE TITLE
Tweak the default timeout

### ISSUE THREAD

**Issue by PeeHaa** [amphp/artax#103]
Currently the [default Artax timeout (120 seconds)](https://github.com/amphp/artax/blob/99b72e4523c6e1e27d39de3a8b422767bcaa48ea/lib/Client.php#L57) is set way too high for any sane setup.

I suggest to use a timeout of 10 - 15 seconds instead. If people need a higher timeout they can set it themselves and the default would be much saner.

**Comment by shtse8** [comment]
Support. It's too high now

**Comment by PeeHaa** [comment]
Is it still too high for you @shtse8 ? Or are you on an old version without db2aac5e390bf84f7cffec07126044b142d6adb8?

**Comment by shtse8** [comment]
Sorry, I am wrong. I was finding how to change the default timeout as 15s is still to high for my case, and searched this post and though the default timeout at the moment was 120s (didn't sure how long it was default, but just feel too long). I suggest to add the options to the doc so we can easily figure out how to change the timeout. I have successfully changed the timeout to 5s now.

**Comment by kelunik** [comment]
> I suggest to add the options to the doc so we can easily figure out how to change the timeout.

Feel free to submit a PR ;-)

I don't have time in the coming days, but maybe afterwards.

**Comment by shtse8** [comment]
Coding is still okay for me. But writing Doc, just forget it. My English is poor.  😭😭😭

**Comment by kelunik** [comment]
@shtse8 See https://amphp.org/artax/configuration.
