### ISSUE TITLE
connections + keep alive + non-continuous CLI apps.

### ISSUE THREAD

**Issue by Danack** [amphp/artax#111]
For CLI apps that run as one-off scripts (as opposed to continuous long running scripts) it is desirable for applications to exit once they've finished doing their work.

With Artax, while connections are still open, they will keep the reactor* open until the keep-alive time is reached, and the connection is closed.

It would be good to be able to have something that does something like monitors all connections, and when they are all idle closes them all, so that they aren't keeping the app open.

I haven't tested this against the current Artax, I was testing against the v1 branch, but I believe it is still an issue.

*I think that's the right name - you kids confuse me with all your async, and your promises.

**Comment by kelunik** [comment]
Yes, this is still an issue. Connections won't be closed, but the watchers will be unreferenced so they don't keep the loop running.

**Comment by kelunik** [comment]
In fact, we already had an issue for that... #98.
