### ISSUE TITLE
Put progress updates back

### ISSUE THREAD

**Issue by bwoebi** [amphp/artax#114]
There should be some mechanism for watching state, timing, redirects etc..

**Comment by kelunik** [comment]
Which ones do we need exactly? I don't think we need timing.

**Comment by bwoebi** [comment]
No, you can get timing yourself by measuring difference of time within callbacks.
I imagine like connection established, tls established, request headers sent, request body sent.

**Comment by kelunik** [comment]
Do we really need them as progress updates? I think it's enough to expose them in `Response` as stats.

**Comment by kelunik** [comment]
@bwoebi ping

**Comment by bwoebi** [comment]
Let's see if it will be needed. Closing for now, it should be possible to add that in a minor?

**Comment by kelunik** [comment]
Yes, should be possible.
