### ISSUE TITLE
Implement backpressure for response bodies

### ISSUE THREAD

**Issue by kelunik** [amphp/artax#115]
Currently there's no backpressure support for HTTP response bodies in the Parser.

**Comment by kelunik** [comment]
Non-2xx responses should not apply backpressure.

**Comment by bwoebi** [comment]
Why shouldn't they?
It's absolutely fine to send a long streamed response to a >= 400 response code.

**Comment by kelunik** [comment]
I don't see a reason why we should accept that. It blocks the connection if not consumed.

**Comment by bwoebi** [comment]
Nobody forces you either to consume a 2xx response (completely).

Once the Stream is destroyed (__destruct()) or fully consumed, we can continue then.

**Comment by kelunik** [comment]
@bwoebi We don't know about it being destroyed currently I think?

**Comment by bwoebi** [comment]
Well, then we need to change that, not different behavior depending on the response status.

**Comment by kelunik** [comment]
It's tricky, not sure what to do there.
