### ISSUE TITLE
Rename `BasicClient` to `DefaultClient`

### ISSUE THREAD

**Issue by PeeHaa** [amphp/artax#121]
I'm not sure what it is but something about the name `BasicClient` really rubs me the wrong way.

Imo at least the naming is better then before where it was just guesswork what the interface and what the implementation was (`Client` <-> `HttpClient`), but I feel `BasicClient` makes me go on a hunt in code and docs to find out what exactly makes this specific implementation "basic".

I personally feel like something `DefaultClient` makes for a better name. As it is some kind of default implementation.

**Comment by kelunik** [comment]
What makes it basic is that it doesn't support any caching for example. I really dislike `DefaultClient` even more than `BasicClient`. We also switched from `DefaultResolver` to `BasicResolver` in `amphp/dns`.
