### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by 2upmedia** [amphp/artax#127]
Can't pin down what's causing the segmentation fault, but here's all of the available information for a possible diagnosis. It seems to happen with responses that have JSON bodies of 1KB+.

This URL is has a large response: 
https://gist.github.com/2upmedia/5e6dd469237a652f43703ccd964d9d0e#file-amp-concurrency-test-php-L94

This one is small: 
https://gist.github.com/2upmedia/5e6dd469237a652f43703ccd964d9d0e#file-amp-concurrency-test-php-L95

You may have to run it several times to see the problem with the following command:

```
RUN_WITHOUT_BENCH=1 php70 -d xdebug.auto_trace=ON -d xdebug.trace_output_dir=/tmp/xdebug_trace amp-concurrent-test.php && echo $?
```

https://gist.github.com/2upmedia/5e6dd469237a652f43703ccd964d9d0e

**Comment by kelunik** [comment]
Which version of PHP do you use? Getting a segfault with PHP 7.0.2, but not with 7.0.12 or 7.0.20.

**Comment by 2upmedia** [comment]
7.0.21 and 7.1.5

**Comment by kelunik** [comment]
It happens on 7.1, too?

**Comment by kelunik** [comment]
I can reproduce the segfault on 7.0.21 locally. @bwoebi Could you have a look please?

**Comment by 2upmedia** [comment]
yes, 7.1.5. 7.0.18 is also affected.

**Comment by 2upmedia** [comment]
exit codes vary between 0, 1, and 139 (when the segfault happens)

**Comment by kelunik** [comment]
This is in fact an xdebug bug, doesn't happen with xdebug not loaded. Could you report it to xdebug?

**Comment by 2upmedia** [comment]
I too thought it had to do with xdebug so I excluded the extension and the segfault will happens.

**Comment by kelunik** [comment]
Did you try 7.1 and 7.0 without xdebug?

**Comment by 2upmedia** [comment]
![image](https://user-images.githubusercontent.com/359945/28221484-6cb02f8a-6891-11e7-8631-612d4bde07fd.png)

**Comment by 2upmedia** [comment]
Looks like 3.0.4 resolved this so I'll close this and report back if the problem creeps up again

**Comment by 2upmedia** [comment]
thanks for resolving this! @kelunik

**Comment by staabm** [comment]
Would be great you could create a valgrind backtrace of the segfault so the underlying bug can be fixed in php-src

**Comment by 2upmedia** [comment]
@staabm I wouldn't mind doing that. I haven't used valgrind before, could you point me in the right direction on how to generate that backtrace?

**Comment by staabm** [comment]
See https://bugs.php.net/bugs-getting-valgrind-log.php

**Comment by 2upmedia** [comment]
@staabm I have a couple of questions that I think could be resolved quicker in real-time. Would you be able to join the #amphp IRC channel?

**Comment by 2upmedia** [comment]
Tried a couple different PHP builds and couldn't get the right combination to get a segfault. I'll keep trying.

**Comment by 2upmedia** [comment]
@staabm
