### ISSUE TITLE
Max num of open connections

### ISSUE THREAD

**Issue by twifty** [amphp/artax#128]
Forgive me if this already exists, but I could not find it while browsing through the source.

Is it possible to set a max parallel limit on the requests? If not, please mark this as a feature request.

I'm porting code which uses a custom curl wrapper to download files. This wrapper has the ability to queue requests and start them only when a download slot becomes available.

**Comment by kelunik** [comment]
We had that based on hosts in Artax v2, but the complexity seems unnecessary for most use cases. What you should do instead is queuing before calling `request` instead.
