### ISSUE TITLE
Amp\Socket\ConnectException on connect failure

### ISSUE THREAD

**Issue by kelunik** [amphp/artax#141]
Currently there's an `Amp\Socket\ConnectException` thrown on connect failure instead of a sub-class of `HttpException`. I'm not sure whether we can change that in v3.x or whether it has to wait for v4.0. If it can't be changed, it has to be documented.

**Comment by bwoebi** [comment]
This should go into a v3.x as the _expectation_ towards the library is to throw a HttpException. Whoever catches a ConnectException currently will almost certainly also catch HttpExceptions.
