### ISSUE TITLE
Error when trying to destruct the socket

### ISSUE THREAD

**Issue by joelwurtz** [amphp/artax#142]
It was happening randomly and i made this error "consistent" when it tries to end the script with last response resolved in the "same time":

```
PHP Fatal error:  Uncaught Error: Unknown socket: 0 in /home/brouznouf/Workspace/asynit/vendor/amphp/socket/lib/BasicSocketPool.php:116
Stack trace:
#0 /home/brouznouf/Workspace/asynit/vendor/amphp/artax/lib/HttpSocketPool.php(104): Amp\Socket\BasicSocketPool->clear(Object(Amp\Socket\ClientSocket))
#1 /home/brouznouf/Workspace/asynit/vendor/amphp/artax/lib/DefaultClient.php(706): Amp\Artax\HttpSocketPool->clear(Object(Amp\Socket\ClientSocket))
#2 [internal function]: class@anonymous->__destruct()
#3 {main}
  thrown in /home/brouznouf/Workspace/asynit/vendor/amphp/socket/lib/BasicSocketPool.php on line 116
PHP Stack trace:
PHP   1. {main}() /home/brouznouf/Workspace/asynit/bin/asynit:0
PHP   2. Asynit\Application->run() /home/brouznouf/Workspace/asynit/bin/asynit:14
```

To reproduce it you can checkout the "feature/amp" branch of this lib https://github.com/jolicode/asynit
do the composer install and then launch the test with this command : `php bin/asynit example`

**Comment by bwoebi** [comment]
I think we should just have checked against the socket id being 0 within amphp/socket @kelunik Catching \Error looks like quite an unclean solution. A resource id will always be positive. If it is 0 the resource will have been destroyed.

**Comment by kelunik** [comment]
@bwoebi The socket should _never_ be destroyed at that point unless it's the final GC round cleaning up everything. See the `amphp/byte-stream` issue I posted.

**Comment by bwoebi** [comment]
Okay, you're right. But still, the fix here is not the proper one. It's now fixed in byte-stream.
