### ISSUE TITLE
Fatal error in Artax socket pool

### ISSUE THREAD

**Issue by brstgt** [amphp/artax#147]
PHP Fatal error:  Uncaught Error: Unknown socket: 0 in /www/jaumo/vendor/amphp/socket/lib/BasicSocketPool.php:116
Stack trace:
#0 /www/jaumo/vendor/amphp/artax/lib/HttpSocketPool.php(104): Amp\Socket\BasicSocketPool->clear(Object(Amp\Socket\ClientSocket))
#1 /www/jaumo/vendor/amphp/artax/lib/DefaultClient.php(706): Amp\Artax\HttpSocketPool->clear(Object(Amp\Socket\ClientSocket))
#2 [internal function]: class@anonymous->__destruct()
#3 {main}  thrown in /www/jaumo/vendor/amphp/socket/lib/BasicSocketPool.php on line 116

**Comment by kelunik** [comment]
Do you use the latest version of Artax?

**Comment by brstgt** [comment]
I updated from 3.0.8 => 3.0.10 right now. Let's see if it's still there

2017-11-09 14:33 GMT+01:00 Niklas Keller <notifications@github.com>:

**Comment by kelunik** [comment]
v3.0.10 explicitly mentions it fixed it, so closing for now. Please upgrade directly to v3.0.12, which is the latest version.

**Comment by rdlowrey** [comment]
Saw this issue in my email ... nice to see folks using amp for real world projects. Wish I had time to contribute these days 😕
