### ISSUE TITLE
Support unix socket

### ISSUE THREAD

**Issue by joelwurtz** [amphp/artax#151]
It works fine when forcing the url into the code. However there is no API to arrive there, since all the parsing stuff will throw an error when using something like `unix:///var/run/program.sock`.

Will gladly do a PR but i don't know which approach should be better :

  * Allow parsing stuff to handle unix scheme ? (will be hard IMO and add a lot of code to reproduce behavior of some PHP functions)
  * Add an extra option, that allows to override the uri of a request (like a remote_socket_endpoint option), which is not parsed (find this better, but may not be the philosophy of this package)

**Comment by kelunik** [comment]
It's quite easy to allow that, see #152.

**Comment by joelwurtz** [comment]
Yes thanks, close this when it's merged (specially for the fix on LocalAddress)

**Comment by kelunik** [comment]
I think we can close this. While `unix://` isn't directly supported, it can be used just fine now.
