### ISSUE TITLE
No request option for a proxy info, as in Guzzle and the cURL library?

### ISSUE THREAD

**Issue by shtaif** [amphp/artax#154]
Is there a way to provide a proxy IP address and port through which to tunnel an HTTP request?

Such as possible with the the Guzzle library, for instance:

```php
$guzzleClient->request('GET', '/', ['proxy' => 'tcp://localhost:8125']);
```

Thanks :)

**Comment by kelunik** [comment]
It's not available per request, but you can pass a custom instance of `HttpSocketPool` to the client and set the appropriate options there. You can also simply set the `HTTP_PROXY` environment variable.

**Comment by shtaif** [comment]
I see, I want to use a different proxy for every request, like a proxy rotator, so `HTTP_PROXY` environment variable will not do.
Regarding the custom instance of `HttpSocketPool`, any documentation for how to do this?

**Comment by kelunik** [comment]
I don't think there's documentation for that, yet, except for the provided PHPDoc. PRs are always welcome. :+1: 

Basically you pass the [custom instance to the `DefaultClient`](https://github.com/amphp/artax/blob/06aa5f35a51060669f5bfd913fb993c387ce0810/lib/DefaultClient.php#L62-L71). You just create a default `HttpSocketPool` and then use [`setOption`](https://github.com/amphp/artax/blob/06aa5f35a51060669f5bfd913fb993c387ce0810/lib/HttpSocketPool.php#L108-L119) with the option constants defined in the class.

**Comment by kelunik** [comment]
I guess this has been solved. If you have further questions, feel free to respond. :+1:

**Comment by zek** [comment]
~~~
        $this->socketPool = new HttpSocketPool();
        $this->socketPool->setOption(HttpSocketPool::OP_PROXY_HTTP, '127.0.0.1:8888');
        $this->client = new DefaultClient(null, $this->socketPool);
~~~
I did it like this but not working.
