### ISSUE TITLE
shuold be used ||  to replace the && operator at if-condition ?

### ISSUE THREAD

**Issue by baykier** [amphp/artax#155]
https://github.com/amphp/artax/blob/06aa5f35a51060669f5bfd913fb993c387ce0810/lib/HttpSocketPool.php#L37

**Comment by kelunik** [comment]
That'd make it always `true`, no?

**Comment by kelunik** [comment]
I believe this has been answered, if you still believe this is a bug, please respond and we can re-open the issue.

**Comment by baykier** [comment]
yeah,that's right,i misunderstanded it , thanks
