### ISSUE TITLE
Leak depending on request timeout

### ISSUE THREAD

**Issue by brstgt** [amphp/artax#157]
Cancellation tokens are not destroyed until tokens expire. If there are a lot requests with very high timeouts this can consume unnecessary amounts of memory.

Is there a reason why they are not destructed requests finish successful?

**Comment by kelunik** [comment]
Do you mean an explicitly passed token or the internally used tokens?

Do you have a script to reproduce?

**Comment by brstgt** [comment]
It's internal tokens. Just run some get requests on a artax instance in a
loop and watch memory grow until request timeout is reached. This also
happens if request promises resolve successfully. You can set timeout to eg
1h to observe it more obviously.

If needed I can provide an example code. But I'm currently AFK

Am 01.02.2018 18:52 schrieb "Niklas Keller" <notifications@github.com>:

Do you mean an explicitly passed token or the internally used tokens?

Do you have a script to reproduce?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/amphp/artax/issues/157#issuecomment-362348044>, or mute
the thread

**Comment by kelunik** [comment]
```php
<?php

use Amp\Artax\Client;
use Amp\Artax\Response;
use function Amp\coroutine;
use Amp\Loop;

require __DIR__ . '/../vendor/autoload.php';

Loop::run(function () {
    $client = new Amp\Artax\DefaultClient;
    $client->setOption(Client::OP_TRANSFER_TIMEOUT, 1 * 60 * 60 * 1000);

    $handler = coroutine(function (int $count) use ($client) {
        for ($i = 0; $i < $count; $i++) {
            /** @var Response $response */
            $response = yield $client->request('http://localhost:1337/');
            yield $response->getBody();
        }
    });

    while (true) {
        $promises = [];
        for ($i = 0; $i < 10; $i++) {
            $promises[] = $handler(100);
        }
        yield $promises;

        var_dump(memory_get_usage(true));
    }
});
```

Ok, I can reproduce it with the following script.

**Comment by kelunik** [comment]
Yes, looks way better now: https://blackfire.io/profiles/compare/767a55d3-772f-42ef-af4f-5336c9a428fe/graph

**Comment by brstgt** [comment]
Boys, you are awesome, altogether @kelunik @bwoebi @trowski

**Comment by kelunik** [comment]
Thanks!

**Comment by kelunik** [comment]
This makes the memory usage of our workers way lower now.

![image](https://user-images.githubusercontent.com/2743004/35759075-b1cc1b8e-0877-11e8-8753-5185dea54dfe.png)
