### ISSUE TITLE
Add option to not save cookies received from server responses

### ISSUE THREAD

**Issue by Bilge** [amphp/artax#168]
I just want a dumb client to send requests and do not want to accept tracking cookies and other garbage state the server sends. I can work around this by creating a new client for every request, but things would go faster if `DefaultClient` did not spend its time parsing and storing cookies I neither want nor use.

**Comment by kelunik** [comment]
The client doesn't store any cookies by default, because it uses a `NullCookieJar` by default.

**Comment by Bilge** [comment]
But it does store them if you use a non-null cookie jar.

**Comment by kelunik** [comment]
No, it doesn't.

https://github.com/amphp/artax/blob/84ba8e2014a81e399541f3dc3a6352bab09c980c/lib/Cookie/NullCookieJar.php#L12-L14

**Comment by Bilge** [comment]
Why are you talking about the `NullCookieJar`? This issue has nothing to do with that. The issue is that, when using a **non**-null cookie jar, `DefaultClient` always parses and saves the cookies back to the jar. I do not want this behaviour.

**Comment by kelunik** [comment]
You wanted a client that doesn't store cookies, which is the default behavior. If you provide a different implementation, then you obviously want cookies to be stored?

**Comment by Bilge** [comment]
I only want to send cookies, not receive them.

**Comment by pcrov** [comment]
I'm not sure why this should be an option rather than just making the cookie jar you need. The interface is pretty straight-forward.
