### ISSUE TITLE
stream_get_meta_data() expects parameter 1 to be resource, null given in lib/DefaultClient.php on line 1093

### ISSUE THREAD

**Issue by brstgt** [amphp/artax#170]
https://github.com/amphp/artax/blob/84ba8e2014a81e399541f3dc3a6352bab09c980c/lib/DefaultClient.php#L1093

[#1] SC\Aerys\Console->output in /www/jaumo/vendor/amphp/aerys/lib/WatcherProcess.php on line 427
[#2] Aerys\WatcherProcess->read in  on line 
[#3] Generator->send in /www/jaumo/vendor/amphp/amp/lib/Coroutine.php on line 74
[#4] Amp\Coroutine->Amp\{closure} in /www/jaumo/vendor/amphp/amp/lib/Internal/Placeholder.php on line 127
[#5] class@anonymous/www/jaumo/vendor/amphp/amp/lib/Deferred.php0x7fa878558264->resolve in /www/jaumo/vendor/amphp/amp/lib/Deferred.php on line 36
[#6] Amp\Deferred->resolve in /www/jaumo/vendor/amphp/byte-stream/lib/ResourceInputStream.php on line 92
[#7] Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure} in /www/jaumo/vendor/amphp/amp/lib/functions.php on line 55
[#8] Amp\call in /www/jaumo/lib/Sensphere/Amp/Loop/ContextDriver.php on line 33
[#9] Sensphere\Amp\Loop\ContextDriver->Sensphere\Amp\Loop\{closure} in /www/jaumo/vendor/amphp/amp/lib/Loop/EventDriver.php on line 38
[#10] Amp\Loop\EventDriver->Amp\Loop\{closure} in  on line 
[#11] EventBase->loop in /www/jaumo/vendor/amphp/amp/lib/Loop/EventDriver.php on line 182
[#12] Amp\Loop\EventDriver->dispatch in /www/jaumo/vendor/amphp/amp/lib/Loop/Driver.php on line 131
[#13] Amp\Loop\Driver->tick in /www/jaumo/vendor/amphp/amp/lib/Loop/Driver.php on line 71
[#14] Amp\Loop\Driver->run in /www/jaumo/vendor/amphp/amp/lib/Loop/EventDriver.php on line 149
[#15] Amp\Loop\EventDriver->run in /www/jaumo/lib/Sensphere/Amp/Loop/DecoratableDriver.php on line 86
[#16] Sensphere\Amp\Loop\DecoratableDriver->run in /www/jaumo/lib/Sensphere/Amp/Loop/ContextDriver.php on line 68
[#17] Sensphere\Amp\Loop\ContextDriver->run in /www/jaumo/vendor/amphp/amp/lib/Loop.php on line 76
[#18] Amp\Loop::run in /www/jaumo/lib/SC/Aerys/InitServer.php on line 231
[#19] SC\Aerys\InitServer->run in /www/jaumo/bin/aerys/server.php on line 13

**Comment by bwoebi** [comment]
Uhm, is that the correct backtrace? There's no call to Artax within aerys/lib/WatcherProcess.php (#1 in trace)

Also: are you by chance using cancellation tokens here (and cancelling them)? That would be my first guess, but just stabbing in the dark given the error message.

**Comment by brstgt** [comment]
Ah sorry! The trace is from the IPC logger in aerys :( It is not the real trace!

We dont use any cancellation tokens except what Artax uses by itself for timeouts (does it?)

**Comment by bwoebi** [comment]
Could you then please get the real trace?

**Comment by brstgt** [comment]
As soon as I have one :)

2018-05-03 16:37 GMT+02:00 Bob Weinand <notifications@github.com>:

**Comment by kelunik** [comment]
@brstgt Do you use cancellation tokens?

Full trace can be found in https://api.travis-ci.org/v3/job/379570248/log.txt.
