### ISSUE TITLE
Stop the client request in 1 second

### ISSUE THREAD

**Issue by sajumani** [amphp/artax#171]
```php
$client = new Amp\Artax\DefaultClient;
```

I want to stop all the client requests with 1s, if they not completed.

Is it possible ? and could you suggest the best way?

**Comment by kelunik** [comment]
There are multiple ways to achieve that. You could use a `TimeoutCancellationToken`, set a [timeout in the client](https://github.com/amphp/artax/blob/84ba8e2014a81e399541f3dc3a6352bab09c980c/lib/Client.php#L17) or use `Amp\Promise\timeout`, but the latter doesn't cancel the operation, but simply "returns" and keeps it running in the background until the script exists or the request completes.

**Comment by sajumani** [comment]
Any good example with multiple promises ?

**Comment by sajumani** [comment]
Am trying to call 2 url

Even one completed execution earlier, and other   The operation was cancelled ....i could not get the result,  both seem " The operation was cancelled"...

**Comment by kelunik** [comment]
@sajumani You'll want to unreference the internal watcher used by the cancellation token. [`TimeoutCancellationToken`](https://github.com/amphp/amp/blob/d561cc9736bc18dd94a2fc9cdae98b616bd92c43/lib/TimeoutCancellationToken.php) does that automatically.

**Comment by sajumani** [comment]
Am trying to call 2 url

Even one completed execution earlier, and other The operation was cancelled ....i could not get the result, both seem " The operation was cancelled"...


What is the solution for this case ?

**Comment by sajumani** [comment]
@kelunik Any solution ? am still waiting ...

**Comment by kelunik** [comment]
@sajumani Deleted the duplicate messages. As I said, use a `TimeoutCancellationToken` instead of a manual timer.

**Comment by sajumani** [comment]
**TimeoutCancellationToken does that automatically.**

Any sample code for this ?

**Comment by kelunik** [comment]
I linked the class, [this line](https://github.com/amphp/amp/blob/d561cc9736bc18dd94a2fc9cdae98b616bd92c43/lib/TimeoutCancellationToken.php#L25) results in the watcher not keeping the event loop alive.

```php
$token = new TimeoutCancellationToken(1000);

// further down - you can share one token for all requests if you want
$promises[$uri] = $client->request($uri, [], $token);
```

The even easier way in your situation where everything has the same timeout:

```
$client->setOption(Client::OP_TRANSFER_TIMEOUT, 1000);
```

**Comment by sajumani** [comment]
Superb @kelunik   it works well...

One final issue,

Am trying to call 2 URL with same timeout.

One completed execution earlier ( before 1 second ), and other request delayed so the operation was cancelled but i could not get the result of completed one both request returned as " The operation was cancelled"...

Any way to capture success one result ?

**Comment by kelunik** [comment]
@sajumani Instead of yielding the array, which is an implicit `Amp\Promise\all`, you can do `list($errors, $results) = yield Amp\Promise\any($promises)`, see https://amphp.org/amp/promises/combinators#any.

**Comment by sajumani** [comment]
@kelunik This is worked thanks...

Timeout latency is always there for extra 200ms...
If i cut it for 1 second, promises terminate at 1.2 Seconds (1200 MS)

Any possibility for cut the timeout exactly as expected ?

**Comment by kelunik** [comment]
@sajumani Did you try `$client->setOption(Client::OP_TRANSFER_TIMEOUT, 1000);`? Does that work better?

**Comment by sajumani** [comment]
@kelunik Yes, this option works much better as expected....

**Comment by sajumani** [comment]
How the promises transfer the data ?

TCP or socket communication ?

**Comment by kelunik** [comment]
Promises are just placeholders for the result and not related to the transfer at all. The client is internally using TCP sockets via PHP's stream API.

**Comment by sajumani** [comment]
@kelunik $client->setOption(Client::OP_TRANSFER_TIMEOUT, 1000);   It terminated the request but the page execution not completed, so i feel the execution happens at backend.  

Am killing the execution with "die()".   It would case any side effect ?

**Comment by kelunik** [comment]
I'm not sure which thing terminated and which thing did not complete, could you elaborate?

**Comment by sajumani** [comment]
$response->getBody();

This is not giving response data;


```
list($errors, $results) = yield Amp\Promise\any($promises);
foreach ($results as $uri => $response) {
	$contents = yield $response->getBody();
}
```

$contents not returning...

**Comment by kelunik** [comment]
Where do you kill the execution with `die()`? Could you provide the full code?

**Comment by sajumani** [comment]
```
$start_at = microtime(true);
$string   = '';

require __DIR__ . '/vendor/autoload.php';

use Amp\Artax\Response;
use Amp\Loop;

Loop::run(function ()use($start_at,&$string) {

	$uris = ["http://google.com/","http://yahoo.com"];

    $client = new Amp\Artax\DefaultClient;
    $client->setOption(Amp\Artax\Client::OP_DISCARD_BODY, true);
	$client->setOption(Amp\Artax\Client::OP_TRANSFER_TIMEOUT, 1000);
    try {
        foreach ($uris as $uri) {
			$promises[$uri] = $client->request($uri);
        }
		list($errors, $results) = yield Amp\Promise\any($promises);
		
		$end_at         = microtime(true);
		$execution_time = ($end_at - $start_at) * 1000;
		$string         = "-- Promises finished at ".$execution_time;
		
        foreach ($results as $uri => $response) {
			**$contents = yield $response->getBody();** // i can't read the response body
            print $uri . " - " . $response->getStatus() . $response->getReason() . PHP_EOL;
        }
		
		$end_at         = microtime(true);
		$execution_time = ($end_at - $start_at) * 1000;
		$string        .= "-- Total Execution completed at ".$execution_time . "\r\n";
		
		die;
		
    } catch (CancelledException $error) {
        print $error->getMessage() . PHP_EOL;
    }catch (Amp\Artax\HttpException $error) {
        // If something goes wrong Amp will throw the exception where the promise was yielded.
        // The Client::request() method itself will never throw directly, but returns a promise.
        print $error->getMessage() . PHP_EOL;
    }catch( Exception $error ){
		print $error->getMessage() . PHP_EOL;
	}
});
```

**Comment by kelunik** [comment]
You'll have to remove `$client->setOption(Amp\Artax\Client::OP_DISCARD_BODY, true);`, otherwise the body gets discarded immediately and will be empty.

**Comment by sajumani** [comment]
Yes works !!! Thank you so much... @kelunik

**Comment by sajumani** [comment]
@kelunik I integrated app with this code past 1 days...

When i run this code in live server(Nginx+php-fpm) with 2000 Request / Second.
The page execution goes high for a while.   Now i stopped our app

I think the request are in queue.

Any idea why it happening ?

**Comment by kelunik** [comment]
@sajumani Try calling `Amp\File\filesystem(new Amp\File\BlockingDriver);` at the start of the script and see whether that helps. Other than that, I don't have any immediate idea.

**Comment by sajumani** [comment]
@kelunik It couldn't helping out, Could you please check when you have time ?

Then it would be more helpful for me
