### ISSUE TITLE
Requests never resolve

### ISSUE THREAD

**Issue by chadmandoo** [amphp/artax#172]
I have tried everything from the examples and this library doesn't resolve its promise. I copy / pasted from the examples and attempted to use my own example and I never get a response back from the request.

```
$client = new DefaultClient();
    // Make an asynchronous HTTP request
    $promise = $client->request('http://www.google.com');
    // Client::request() is asynchronous! It doesn't return a response. Instead, it returns a promise to resolve the
    // response at some point in the future when we've received the headers of the response. Here we use yield which
    // pauses the execution of the current coroutine until the promise resolves. Amp will automatically continue the
    // coroutine then.
    /** @var Response $response */
    $response = yield $promise;
    // Output the results
    printf(
      "HTTP/%s %d %s\n\n",
      $response->getProtocolVersion(),
      $response->getStatus(),
      $response->getReason()
    );
    // The response body is an instance of Message, which allows buffering or streaming by the consumers choice.
    // Simply yielding a Message buffers the complete response body.
    $body = yield $response->getBody();
    print $body . "\n";
```

I'm not sure how to go about debugging why its not working because i never get anything back beyond it just hanging.

**Comment by chadmandoo** [comment]
Ok I have found something of interest. This does work however if I am performing this in another class it seems to not work. Am I top wrap each in a promise?

**Comment by kelunik** [comment]
Please post your full code. I guess you're creating a generator with some call, but don't turn it into a coroutine anywhere.

**Comment by chadmandoo** [comment]
You are right. I moved the above code into my onData method and it works. I think its my ignorance in how to handle this. I had out the above code in another class and called it. If yiu have any examples of that it would be helpful otherwise this could be closed.

**Comment by kelunik** [comment]
@chadmandoo See https://github.com/amphp/amp/pull/226 for more documentation, still have to merge that PR.
