### ISSUE TITLE
Allow raw sending of form fields?

### ISSUE THREAD

**Issue by thomasnlv21** [amphp/artax#173]
Hi, First of all, sorry if this isn't the right place to ask this question, please close it/move it elsewhere if this is irrelevant here.
I m trying to replace traditional curl calls to a prestashop server (using this [provided library](https://github.com/PrestaShop/PrestaShop-webservice-lib/blob/master/PSWebServiceLibrary.php) ) with artax async calls.
GET requests are ok but i m having trouble when posting XML. With Artax i do the following : 
```
$body = new FormBody();
$body->addField('',$rawxml);
```
The problem seems to be that the server does not accept the encoded XML string:

> String could not be parsed as XML

even if the content-type IS x-www-form-urlencoded when using the prestashop server standard library, it only accepts it as raw.
As a test, i tried to change getFormEncodedBodyString() in FormBody.php
`    private function getFormEncodedBodyString(): string {
        $fields = [];

        foreach ($this->fields as $fieldArr) {
            list($name, $value) = $fieldArr;
            $fields[$name][] = $value;
        }

        foreach ($fields as $key => $value) {
            $fields[$key] = isset($value[1]) ? $value : $value[0];
        }
          return implode("&",$fields);
        //return \http_build_query($fields);
    }`
That simple change made the 3rd party API accept the request.
So i know, it is not an Artax issue, but do you think allowing raw sending of form fields via an option is something that could make sense in some cases or not?

**Comment by kelunik** [comment]
You need to set the body directly, it's not supposed to be a form, i.e. `$request->setBody($rawXml);`.

**Comment by thomasnlv21** [comment]
Works like a charm, Thanks a lot!
