### ISSUE TITLE
how to get request socket

### ISSUE THREAD

**Issue by hooklife** [amphp/artax#180]
https://docs.docker.com/engine/api/v1.39/#operation/ContainerAttach 
docker API send an upgrade HTTP request, the TCP connection can now be used for raw.

so, I want to get some request TCP connection

thanks

**Comment by kelunik** [comment]
We currently don't support upgrade request. You can use `amphp/socket` to make the HTTP request and upgrade manually, [as it is done in `amphp/websocket-client`](https://github.com/amphp/websocket-client/blob/aff808025637bd705672338b4904ad03a4dbdc04/src/Rfc6455Connector.php).
