### ISSUE TITLE
Error on rc-5 release

### ISSUE THREAD

**Issue by PatrickLouys** [amphp/artax#68]
`Deprecated: Amp\ReactorFactory is deprecated and scheduled for removal. Please update code to use the Amp\getReactor() function instead. in D:\wwwroot\gp_dev_patrick\vendor\amphp\amp\lib\ReactorFactory.php on line 16`

It works with dev-master. Would be great if you could release another version with the fix that is already in dev-master so that we don't have to use dev-master as version.

Thanks :)

**Comment by rdlowrey** [comment]
Guys I apologize for the long delay here. The only excuse I've got is real life and holidays. I've tagged rc6 and should be more responsive going forward.
