### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by danielmitchell2415** [amphp/artax#77]
I built a crawler based on artax using the ParallelCrawler example from v 0.7. Everything works smooth except for one thing: the memory footprint. It always increases by each new url that has been consumed.
Here is an example that demonstrates that memory increases as we add more urls into the mix:

``` php
<?php
Amp\run(function() {
    $client = new Amp\Artax\Client;

    $tmpRequests = [];
    $requests = ['http://bing.com','http://google.com','http://microsoft.com','http://yandex.com','http://twitter.com','http://live.com','http://wordpress.com','http://imgur.com','http://pinterest.com','http://ask.com','http://msn.com','http://alexa.com','http://dropbox.com'];
    for($i=0;$i<50;$i++) $tmpRequests[] = $requests[array_rand($requests)];

    // Dispatch two requests at the same time
    $promiseArray = $client->requestMulti($tmpRequests);

    try {
        // Yield control until all requests finish (magic sauce)
        echo "Memory::start::".number_format(memory_get_usage(true));

        $responses = (yield Amp\all($promiseArray));

        echo "Memory::end::".number_format(memory_get_usage(true));

        foreach($responses as $oneResponse)
        {
            var_dump($oneResponse->getStatus(), $oneResponse->getStatus()); 
        }

    } catch (Exception $e) {
        echo $e;
    }
});   
```

**Comment by rdlowrey** [comment]
Based on the code sample here the memory usage is expected to increase with each request because at no point are you freeing the resources associated with the individual requests. By yielding the `all()` combinator function promise you're saying *"keep everything in memory until all of these responses complete."*

Also note that each `Response` instance keeps a reference to the `Request` object used to retrieve it. Because all of your responses are still in memory at the time you do the memory usage check this means *everything* you've created so far in the script is still in memory.

Instead of dispatching all of your concurrent requests at once (and thus keeping all of them in memory at the same time) you could instead request only a few at a time.

Another issue you may be running into is this: by default the client will buffer response entity bodies as strings upon completion. So if you're retrieving large files this will put them entirely into memory. If you instead wish to keep them in stream form you should do the following prior to making requests:

```
$client->setOption('bufferbody', false);

// ... then when you process the entity bodies:
$body = stream_get_contents($response->getBody());
```

This approach will allow you to only buffer the individual entity body you're working with at the time instead of storing *everything* in memory at once.

**Comment by danielmitchell2415** [comment]
You're right, that example code keeps the memory blocked until all the promises are resolved. The thing is that the memory issue persists even if the requests are run async. Here is a piece of the crawler that I'm using:
```php
<?php
class Crawler{
.....
	public function start()
	{
		$request_urls = $this->getRecordsFromDB(); 
	
		$this->reactor->immediately(function() use ($request_urls)
		{
			$counter = 0;
			foreach($request_urls as $uri)
		    {
		    	$baseUri = new Amp\Artax\Uri($uri);

		    	if(!$this->isExclusion($baseUri))
		    	{
		    		$counter++;
		    		if($counter > $this->maxThreads) $this->enqueueRequest($uri);
		    		else $this->doRequest($uri);
		    	}
		    }
		});
		
		$this->reactor->run();
	}


    private function doRequest($uri)
    {
    	$uri_hash = md5($uri);
    	
    	$request = (new Amp\Artax\Request)->setUri($uri);
    	
    	$requestHandler = function(Exception $e = null, $response = null) use ($request)
	    {
		    if($e) $this->onError($request, $e);
		    else $this->onResponse($request, $response);
		};
        
		$this->promises[$uri_hash] = $this->client->request($request);
        $this->promises[$uri_hash]->when($requestHandler);
    }

    private function onResponse(Amp\Artax\Request $request, Amp\Artax\Response $response)
    {
    	$uri = new Amp\Artax\Uri($request->getUri());
        
        echo "Completed $uri -- ", $response->getStatus(), ' ', $response->getReason(), "\n";
        
        if ($response_code == 200)
        {
            $body = $response->getBody();
            
	        $dom = new DOMDocument;
	        
	        if (@$dom->loadHTML($body))
	        {
				//newly found links are pushed in the queue            	
				$this->parseLinksFromRawBody($uri, $dom);
	        }
        }
        
		unset($this->promises[md5($uri)]);
        
        $this->dequeueNextRequest();
    }

    private function onError(Amp\Artax\Request $request, $e)
    {
        $uri = $request->getUri();
        
        echo "Error retrieving {$uri}::".$e->getMessage()."\n";
        
		unset($this->promises[md5($uri)]);
                
        $this->dequeueNextRequest();
    }

    private function dequeueNextRequest()
    {
    	if (!empty($this->requestQueue))
        {
        	$uri = array_shift($this->requestQueue);	
        	$this->doRequest($uri);
        }
        else
        {
			$this->reactor->stop();
			die;
		}
	}

    private function enqueueRequest($uri)
    {
    	$this->requestQueue[md5($uri)] = $uri;
    }
.....

}
?>
```
After 30 minutes it has already consumed 450 Mb of RAM and still going up.  From what I understand from your comment, while the reactor is running the memory used by the $responses does not get flushed. So if new links are pushed into the queue, as it always happens in case of new found pages, the script keeps getting larger. Is this the case ?  If so, is there any way I ca use artax for continuous crawling ?

"Because all of your responses are still in memory at the time you do the memory usage check this means everything you've created so far in the script is still in memory." 

Can you tell me when , or where in the code, a Response is garbage collected ? I think that in the crawler code, the responses are never flushed, but are stacked somewhere, and I can't find where exactly. I think that memory pointers to a previous, and used, Responses, are still hanging somewhere. After the onResponse() function is triggered, the $response var should be nullified, right ?

One more thing: even if the 'bufferbody' option is set to false, the resource is still transformed to string on each new request in Client->inflateGzipBody():611

```php
    private function inflateGzipBody(Response $response) {
        $src = $response->getBody();
        if (is_resource($src)) {
            $destination = fopen('php://memory', 'r+');
            fseek($src, 10, SEEK_SET);
            stream_filter_prepend($src, 'zlib.inflate', STREAM_FILTER_READ);
            stream_copy_to_stream($src, $destination);
            rewind($destination);
            $response->setBody($destination);
        } elseif (strlen($src)) {
            $body = gzdecode($src);
            $response->setBody($body);
        }
    }
```
I have a question about this code: where do you fclose() the $destination resource handler ? This handler has to be closed at some point the in code to free the memory, right ?

To better test this issue, just run the ParallelCrawler from the v. 0.7 of Artax, and you'll see that the memory is always going up as new urls are parsed.

Can you help me with this crawler approach to Artax ?

**Comment by kelunik** [comment]
Closing, please retry with Artax v3 once its out.
