### ISSUE TITLE
Invalidate Artax cache

### ISSUE THREAD

**Issue by pensiero** [amphp/artax#82]
I noticed that even if the body of a request is updated, Artax keep it in cache for a lot of minutes (maybe hours)... how can I invalidate the cache?

Thanks

**Comment by rdlowrey** [comment]
Would you mind elaborating a little further on this? HTTP response bodies shouldn't ever be cached ... Perhaps you could provide a reproduce script?

**Comment by pensiero** [comment]
Sure, after updating the body of the `$url`, I tried with a simple:

```
$request = (new ArtaxRequest)
    ->setUri($url)
    ->setMethod('GET');
    
$ampResponse = Amp\wait((new ArtaxClient)->request($request));
$ampResponse->getBody() == file_get_contents($url); // FALSE (but it should be TRUE)
```

**Comment by rdlowrey** [comment]
Sorry I was unclear: could you post an actual snippet that I can run myself that demonstrates the problem? I need a full script that I can copy/paste to reproduce the issue. I'm happy to help, I just need a full repro script.

**Comment by pensiero** [comment]
I can give you the script, but you have to specify an URI and change the content of that URI, can you?

**Comment by kelunik** [comment]
Without a URL it doesn't make sense. Did you view a diff between the two bodies? It's probably some CSRF token or so that differs.

**Comment by kelunik** [comment]
Closing for now, will reopen if there's a repro case.
