### ISSUE TITLE
Question : Non blocking request

### ISSUE THREAD

**Issue by harikt** [amphp/artax#83]
Hi, 

I have a question regarding non blocking request. I wanted to send the request, but I don't care to wait for the response. Is there a way to achieve it ?

Say calling a url : `http://example.com/post/hello?w=222` . Just a dummy one.

Thank you.

**Comment by staabm** [comment]
Hi harikt,

see the example in the readme:
https://github.com/amphp/artax#simple-uri-get

as long as you dont call `$response = Amp\wait($promise);` it doesnt block.

**Comment by harikt** [comment]
Thank you.

I will test it.

**Comment by kelunik** [comment]
@harikt: Can we close this issue?

**Comment by harikt** [comment]
Basically the documentation seems wrong and I don't remember where I ended up.
