### ISSUE TITLE
Different response using PHP 5.5

### ISSUE THREAD

**Issue by kelunik** [amphp/artax#92]
Fetching the following URL with Artax results in a different response on 5.5 than on 5.6 or 7.0. I still can't figure out why. `file_get_contents` works fine on all versions.

https://opacplus.bib-bvb.de/TouchPoint_touchpoint/start.do?Query=205%3D%22BV021286998%22&Language=De&SearchProfile=

**Comment by kelunik** [comment]
Command line snippet to reproduce the behavior:

`php -r 'include __DIR__ . "/vendor/autoload.php"; $resp = Amp\wait((new Amp\Artax\Client)->setOption(Amp\Artax\Client::OP_VERBOSITY, Amp\Artax\Client::VERBOSE_ALL)->request("http://gateway-bayern.de/BV042035367"));' | less`

**Comment by bwoebi** [comment]
The issue is PHP 5.5 defaulting to SSL v2 with the tcp protocol (WTF????) and the server rejecting this.

Let me investigate further...
