### ISSUE TITLE
Severed Connection for PHP builtin server with localhost.

### ISSUE THREAD

**Issue by Danack** [amphp/artax#94]
Server code:

```
<?php
echo "Hello world";
exit(0);
```

Client code:

```
<?php

require __DIR__.'/vendor/autoload.php';

use Amp\Artax\Client as ArtaxClient;

$client = new ArtaxClient();

$request = (new Amp\Artax\Request)
    ->setMethod('POST')
    ->setUri('http://localhost:8000/?foo=bar');

$promise = $client->request($request);

try {
    $response = \Amp\wait($promise);
}
catch (Amp\Artax\SocketException $se) {
    echo $se->getMessage() . "\n";
}
```

Running the above server code with PHP's builtin server with `php -S 0.0.0.0:8000 -t htdocs/` works fine.

Running the above server code with PHP's builtin server with `php -S localhost:8000 -t htdocs/` gives the exception message: `Connection to server severed before the request write could complete.`

Obviously could be a bug in PHP src....

**Comment by kelunik** [comment]
@Danack please check whether it's binding to `127.0.0.1` (IPv4) or `::1` (IPv6) or both.

**Comment by Danack** [comment]
It looks like it's binding to IPv6. Using corrected code to access via localhost:


```
<?php
require __DIR__.'/vendor/autoload.php';

use Amp\Artax\Client as ArtaxClient;

$client = new ArtaxClient();

$request = (new Amp\Artax\Request)
    ->setMethod('GET')
    ->setUri('http://localhost:8000/?foo=bar');

$promise = $client->request($request);

try {
    $response = \Amp\wait($promise);
}
catch (Amp\Artax\SocketException $se) {
    echo $se->getMessage() . "\n";
}
```

still shows the same error of a severed connection.

**Comment by kelunik** [comment]
What did you correct? Try it with `http://[::1]:8080/?foo=bar` instead.

**Comment by Danack** [comment]
> What did you correct?

Sorry - got confused, thought I had posted the example originally with 127.0.0.1 - and so thought I had 'corrected' it to localhost.

Anyway, testing it with:

```
$request = (new Amp\Artax\Request)
    ->setMethod('GET')
    ->setUri('http://[::1]:8000/?foo=bar');
```

Gives a different error:

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid header; scalar or one-dimensional array of scalars required' in ./vendor/amphp/artax/lib/Message.php:115
Stack trace:
#0 ./vendor/amphp/artax/lib/Client.php(305): Amp\Artax\Message->setHeader('Host', NULL)
#1 ./vendor/amphp/artax/lib/Client.php(184): Amp\Artax\Client->normalizeRequestHostHeader(Object(Amp\Artax\Request), Object(Amp\Artax\Uri))
#2 ./vendor/amphp/artax/lib/Client.php(130): Amp\Artax\Client->finalizeRequest(Object(Amp\Artax\RequestCycle))
#3 ./test.php(14): Amp\Artax\Client->request(Object(Amp\Artax\Request))
#4 {main}
  thrown in ./vendor/amphp/artax/lib/Message.php on line 115
```

**Comment by kelunik** [comment]
Just to make that one clear: When you start the PHP built-in server, what's the output?

```
[17:32:42][2149][~/GitHub/kelunik/artax] $ php -S [::1]:8000 -t .
PHP 7.1.0-dev Development Server started at Mon Aug  8 17:32:52 2016
Listening on http://[::1]:8000
Document root is /home/kelunik/GitHub/kelunik/artax
Press Ctrl-C to quit.
```

Looking for `Listening on ...`

**Comment by kelunik** [comment]
I've just pushed a fix for the IPv6 host header failure to `master` and `1.x`.

**Comment by kelunik** [comment]
I've just verified that this is the correct header to send for IPv6: https://bugzilla.mozilla.org/show_bug.cgi?id=45891, was too lazy to read the RFC.

**Comment by kelunik** [comment]
Closing, as this is an issue with the built-in PHP server, it only binds to the IPv6 loopback interface, not the IPv4 one. Thanks for the report of the other issue!
