### ISSUE TITLE
Lift Uri class out into a separate package

### ISSUE THREAD

**Issue by DaveRandom** [amphp/artax#96]
The `Uri` class is useful in many contexts, not just an HTTP client.

Moreover, it even [contains code](https://github.com/amphp/artax/blob/master/lib/Uri.php#L174-L182) that's nothing to do with HTTP and useless within Artax!

Please can this be separated out into another lib? This would enable my composer.json to be clearer about what I actually require - I don't want to have to pull down a whole HTTP client just to be able to resolve URIs.

In the interests of retaining backwards compat with any code that currently uses `Amp\Artax\Uri`, I propose either `class_alias()` in a composer `"files"` autoload, or if you want to retain absolute compat for code that does not use composer (which I suspect is 0%) then could simply have `class Uri extends ... {}` in the existing `Uri.php` file.

**Comment by PeeHaa** [comment]
> retaining backwards compat with any code that currently uses Amp\Artax\Uri, I propose either class_alias() in a composer "files" autoload

Isn't a v2 in the works as we speak? Break all the BC!

**Comment by kelunik** [comment]
I'm currently working on it. I think we should make some minor API changes.

**Comment by kelunik** [comment]
See https://github.com/amphp/uri.

**Comment by DaveRandom** [comment]
@kelunik indeed, I think there's also scope for a couple of function primitives (`canResolve()` and `resolve()`), plus it would be good to have a better exception hierarchy and maybe the ability to have a user-defined default port map (or at least to add entries?).

**Comment by kelunik** [comment]
I don't think we will change Artax at all here but instead remove it in the upcoming rewrite of Artax that will be done after Amp v2. But we might deprecate it in the next release then.

**Comment by kelunik** [comment]
@DaveRandom Could you add all API changes you want to see as separate issues in the new repository?
