### ISSUE TITLE
Options missing from HttpClient interface

### ISSUE THREAD

**Issue by DaveRandom** [amphp/artax#99]
At the moment, options (this `OP_*` constants) are defined on the `Client` class rather than the `HttpClient` interface. However, the interface defines `setOption()`. This means the it's not currently possible to decouple code that needs to set options from the concrete implementation.

I realise that potentially there may be implementation-specific options, but many/most options are generic and should be implemented by any concrete class. Those generic options should be moved to the interface (or possibly an `Options` enum-but-not-enum-because-PHP?) so that code which needs to set such "generic" options only needs to `use` the interface.

Examples of such options that are, IMHO, required for a minimum viable HTTP client implementation are `OP_DEFAULT_USER_AGENT` and `OP_FOLLOW_LOCATION`. There are plenty more.

**Comment by staabm** [comment]
as long as the options are not impl-specific having those defined on the interface itself sounds like a good idea

**Comment by kelunik** [comment]
@DaveRandom `OP_FOLLOW_LOCATION` should be in the interface as it changes how the client behaves, but I'm not sure `OP_DEFAULT_USER_AGENT` has to be there. The default user agent shouldn't be changed at runtime, instead, if you need another user agent, change it for a single request.

**Comment by bwoebi** [comment]
There technically are some options which more belong to the interface and and some belonging more to the class.

But ultimately that's going to be very confusing.

To be honest, I'm not even sure why Client and HttpClient are separate class and implementation... Possibly for testing, but it's easy to have mocks overriding the impl.

**Comment by kelunik** [comment]
> To be honest, I'm not even sure why Client and HttpClient

Because interface all the things. \o/

**Comment by kelunik** [comment]
Done in v3.
